### ISSUE TITLE
Setup eBMS on live data warehouse

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#1]
Live site to be moved onto:
http://www.butterfly-monitoring.net/mydata

Linked to new Indicia warehouse (to be named warehouse2).

**Comment by BirenRathod** [comment]
The warehouse2 has now been identified by the domain name which is warehouse2.indicia.org.uk and it is now on live.

**Comment by Gary-van-Breda** [comment]
Can we have
1) A google maps api key: following changes at Google, we now need one.
2) the summary_builder warehouse module switched on.
3) confirmation that the cache_builder warehouse module is switched on.
4) all the permissions for tables in the warehouse checked for the normal and report user: at the moment the forms are complaining about lack of permissions on the location_attributes and samples tables.

**Comment by BirenRathod** [comment]
Hello Gary

1.  I stored a new generated the google api key. Gary, could you please make sure that georeference should point at google map in the report file.
2.  The sunmmary_builder has switched on and cache_builder was already on.
3.  All permission has been reassigned.

I have also implemented the style problem of the disabled links under the "Mydata" submenu.

**Comment by BirenRathod** [comment]
Hello Gary

$google_maps_api_key variable has got now value stored of api_key in the helper_config.php file. I think repository has not been upgraded with latest code to get value from iForm admin form. I will check with John about this.

**Comment by Gary-van-Breda** [comment]
Can we get the the EBMS iform (and client_helpers) brought up to the develop Git branch?

**Comment by Gary-van-Breda** [comment]
I'm getting a RefererNotAllowedMapError for pages which use the google map api: do we need to tell it which forms are using the map?

**Comment by BirenRathod** [comment]
I think you just need to change the setting from yahoo geo planet to google place search. which should be ok.

**Comment by Gary-van-Breda** [comment]
Its not the georeferencing that is the problem. Can you confirm that the referrers under the credentials includes "http://butterfly-monitoring.net/*" as well as "http://www.butterfly-monitoring.net/*"? Thanks

**Comment by Gary-van-Breda** [comment]
I have swapped all the georeferencing to use the google api.

**Comment by BirenRathod** [comment]
this " *.butterfly-monitoring.net/* " credential included. is that sufficient or not? with both end * included.

**Comment by Gary-van-Breda** [comment]
It's still not working properly. If I put "http://www.butterfly-monitoring.net/input-timed-count" into Firefox, the map is displayed, but not if I use "http://butterfly-monitoring.net/input-timed-count" . I'm not sure there should be a full-stop at the front of the credential.
Also can we uncomment the $cookie_domain in the settings.php, and set it to ".butterfly-monitoring.net": this should allow the same login to be used on both variations of the url (with or without the "www.").

**Comment by BirenRathod** [comment]
Well, I found two problems.
1. site was not redirecting if I use butterfly-monitoring.net url in the address bar as logged in. So I amended the settings.php and assigned the $base_url value with the website address.
2. I also add the credential without full stop at the front of the url.

Let me know if you still see the problem.

**Comment by Gary-van-Breda** [comment]
Nope: problems fixed.

**Comment by Gary-van-Breda** [comment]
I've identified 4 drupal modules on the dev system, that are not on Live:
1) Terms of use
2) user registration notification
3) FE Block
4) UUID Features.
I'm not sure about the last two, but could we have the first two installed? Thanks

**Comment by BirenRathod** [comment]
Hello Gary
I uploaded first and two modules. what is FE block module? UUID features is already exist.

**Comment by Gary-van-Breda** [comment]
I don't know what we use FE Block for (if anything), so I'm not bothered if it isn't there.
As I see it now, the main task now are as follows (in order)

1. bring the iform & client_helpers up to the Git develop branch, as this has the Luxembourg changes. Can you do this Biren? We then need to:
2. configure the new site entry form (and add the attribute from issue #7) (me)
3. check the updated walk entry form (adding the attribute in issue #3) (me)
4. we need the countries loaded in (issue #2) (Biren?). The site entry form will not work without them.
5. copy over the ukbms_year_index_values warehouse module from warehouse1 to warehouse2, and enable it (Biren?)

I don't know if the other issues have to be addressed before this goes live.

**Comment by BirenRathod** [comment]
Hello Gary
1. I have hpdated the iform folder from Git repository.
4. I'm in the process of uploading countries shape files. As soon as I done that, let you know.
5. I have copied the ukbms_year_index_values onto the warehouse2.

**Comment by Gary-van-Breda** [comment]
Hi Biren,

- Can you ensure that the iform client_helpers and media folders are updated from their respositories as well? It doesn't look like the new EBMS form is installed yet.
- Will the countries be available as location records within the warehouse, or are they just there as a layer in the geoserver?
- Can you switch on the  ukbms_year_index_values warehouse module in the modules config item in file application/config/config.php on warehouse2?

**Comment by BirenRathod** [comment]
Hello Gary

-  It has updated from the repository, but could tell me which forms are you after?
- I'm uploading the layers, soon will be available. I will let you know once it has done. 
- I now have enabled this module.

**Comment by Gary-van-Breda** [comment]
- The form I'm looking for is ebms_sectioned_transects_edit_transect.php. This also has associated .js, .css and .en.php files. I'm also expecting updated versions of the ukbms_sectioned_transects_input_sample.php and timed_count.php forms (plus their associated files).
- My question is really that there are 2 ways the countries could be made available to us: 1) they are a layer within the geoserver (driven by a shape file behind the scenes), or 2) they are individual location records within the warehouse (e.g. there are 5 on warehouse1: England, Wales, Northern Ireland, Eire and Scotland). Which of these are you doing?
- Thanks: module is good.

**Comment by BirenRathod** [comment]
- I couldn't find the ebms_sectioned_transects_edit_transect.php in the repository, is it possible to send me the repository link? rest two are already upgraded in the prebuilt_forms folder.
- I'm doing the second one. would be more appropriate? unless the first one has got any special benefit.

**Comment by Gary-van-Breda** [comment]
- https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/ebms_sectioned_transects_edit_transect.php
- Excellent, second one is good - no need for the first.

Thanks

**Comment by BirenRathod** [comment]
Hello Gary
Thanks for the link. 
I copied files only from master branch before. So I have now copied all files from develop branch.

**Comment by BirenRathod** [comment]
Hello Gary

I have uploaded the shape files for England, Scotland, Wales, Northern Ireland, GB, UK. I will upload more in due course. Do you have any country which has got priority? Let me know.

**Comment by DavidRoy** [comment]
European countries should be priorities.  The first priority is Luxembourg.

Is there not an option to load a single world layer of countries, rather than do them individually?

**Comment by BirenRathod** [comment]
My Next layer will be a single world layer but it doesn't have a layer for GB. So, I first uploaded the GB and Britain's countries.

**Comment by DavidRoy** [comment]
GB is not as important because eBMS will not be used for the UK as we already have the system for the UKBMS.

**Comment by BirenRathod** [comment]
I know, but this is about world countries which was missing in next layer.

**Comment by BirenRathod** [comment]
World countries are uploaded in to the warehouse. So far so good. Indexed and validated. looks good on the map.

**Comment by Gary-van-Breda** [comment]
Hi Biren,
Can you also update the data_entry_helper.php file from the develop branch?
Thanks

**Comment by Gary-van-Breda** [comment]
I have now updated the Site entry form and added the new location attribute (issue #7 ). It currently has a JS error, which should be fixed by the updated to the data_entry_helper.php mentioned above.

**Comment by BirenRathod** [comment]
I have updated the data_entry_helper.php file.

**Comment by Gary-van-Breda** [comment]
Hi Biren,
Can I have the following files copied over as well from the develop branch? I've enclosed the links

https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/ukbms_sectioned_transects_input_sample.php
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/css/ukbms_sectioned_transects_input_sample.css
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/js/ukbms_sectioned_transects_input_sample.js
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/timed_count.php

Thanks
Gary

**Comment by BirenRathod** [comment]
Those are already upgraded on the live site.

**Comment by Gary-van-Breda** [comment]
Not on the warehouse - into the Drupal7 iform client_helpers.Thanks

**Comment by Gary-van-Breda** [comment]
Apologies - I meant to say, please make sure it is the deveop branch code. Thanks

**Comment by BirenRathod** [comment]
Yes, It has got develop branch code last updated on 16th and 17th January one. It is on the client_helpers of drupal7 folder.

**Comment by Gary-van-Breda** [comment]
OK thanks: I had to clear the drupal caches. data_entry_helper looks good too, so the Luxembourg changes are in.

Issues outstanding:
- The country list displayed on the site form now includes all world countries - is this OK David, or should we restrict this to a specific subset?
- There is an issue with the timed_count entry form when dealing with multiple coordinate systems - it does not display the correct set.
- There is a warning displayed in the walk entry form when displaying an attribute which is only attached to the Section.
- When there is a single location type, the ebms site form is not updating the max number of sections.

I have fixes for these last 3 that I am testing right now.

**Comment by Gary-van-Breda** [comment]
OK Biren, I've dropped the fixes into the develop branch, so can I have the following files deployed into the drupal site:
ebms_sectioned_transects_edit_transect.php, ebms_sectioned_transects_edit_transect.js, timed_count.php and ukbms_sectioned_transects_input_sample.php

Thanks
Gary

**Comment by BirenRathod** [comment]
I have upgraded on to live site.

**Comment by DavidRoy** [comment]
@Gary-van-Breda. Re: The country list displayed on the site form now includes all world countries - is this OK David, or should we restrict this to a specific subset?

I have logged in but can't access the 'My sites' page to test and come to a view on this

**Comment by Gary-van-Breda** [comment]
Hi David - I've just given you normal data recorder and country manager roles, so you should now be able to see the My sites page.

**Comment by DavidRoy** [comment]
Could we remove certain countries from the list - where we don't want the eBMS system to be used (e.g. in the UK because we have the ukbms/mydata system)?

Also, if a country is chosen, a site can still be located outside of the country.  Could the country selection reflect where the site is selected on the map?

**Comment by Gary-van-Breda** [comment]
Removing countries: that is OK, I have some code ready.
RE the automatic completion of the country field on creation of a site on the map: Biren, do we have a geoserver on warehouse2?

**Comment by BirenRathod** [comment]
Hello Gary

Which country do I have to remove? this is for country added in the location, right? 

Yes, we have Geoserver setup. http://warehouse2.indicia.org.uk:8080/geoserver

**Comment by DavidRoy** [comment]
@BirenRathod no need to remove countries from the spatial layer, just the drop-down list for users to select.  No need for any action from you, thanks

**Comment by Gary-van-Breda** [comment]
OK Luxembourg maps are now working.
I'm currently testing the automatic country lookup.

**Comment by Gary-van-Breda** [comment]
Hi Biren,
Can I have the following files copied over from the develop branch? I've enclosed the links

https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/ebms_sectioned_transects_edit_transect.php
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/js/ebms_sectioned_transects_edit_transect.js

Thanks
Gary

**Comment by BirenRathod** [comment]
Hello Gary

Both files gone live now.
Biren

**Comment by Gary-van-Breda** [comment]
OK, I've put in the configuration.

David, the automatic country lookup is now in place, and all non-Europeanish countries removed. If you want to have a check of the list, I can remove/add any you wish. I have taken out the UK (and its sub-countries).

**Comment by Gary-van-Breda** [comment]
As far as I know the site is now sorted.

**Comment by xaviermestdagh** [comment]
Thanks for change on the number of sections. 
In the process of creating a new site, I clicked on "Save" at the bottom of "Site details". It induced a switch in the maps from ACT (LU maps) to Google maps. ACT maps are not anymore visible, in the "Your route" tab neither, and even by re-editing the site. 
If I create a new site, ACT maps are ok.

**Comment by Gary-van-Breda** [comment]
Xavier, Which site did you have the problems on?

**Comment by xaviermestdagh** [comment]
If by site you mean 
web site: butterfly-monitoring
Sampling site: any sites (country or my sites). ACT maps are well displayed until the button save is not pushed...

Envoyé depuis IBM Verse


   Gary-van-Breda --- Re: [BiologicalRecordsCentre/eBMS] Setup eBMS on live data warehouse (#1) --- 
    De :"Gary-van-Breda" <notifications@github.com>A :"BiologicalRecordsCentre/eBMS" <eBMS@noreply.github.com>Cc :"xaviermestdagh" <xavier.mestdagh@list.lu>, "Comment" <comment@noreply.github.com>Date :ven., 10 févr. 2017 15:20Objet :Re: [BiologicalRecordsCentre/eBMS] Setup eBMS on live data warehouse (#1)
  
  Xavier, Which site did you have the problems on?

**Comment by DavidRoy** [comment]
Now closing this issue.  Is suggest that bugs are raised as new issues.
