### ISSUE TITLE
Sections drawing

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#12]
@Gary-van-Breda : I manage to draw the section one, but I have trouble to draw the others. No reactiosn while pushing buttons "S2" (or other number), "Save route", "Complete Section details", "Insert sections", "Remove section"...

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you deploy the develop branch versions of the following files into the EBMS site? Thanks.

https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/ebms_sectioned_transects_edit_transect.php
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/css/ebms_sectioned_transects_edit_transect.css
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/js/ebms_sectioned_transects_edit_transect.js

These changes also address issue #13

**Comment by BirenRathod** [comment]
Gary, all this files have been upgraded.

**Comment by xaviermestdagh** [comment]
Thanks. This issue #12 is ok for me.
