### ISSUE TITLE
ERROR during log in

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#14]
I had trouble to log in, I  requested a new password, got a one-time login link and got this while using the link:

You have just used your one-time login link. It is no longer necessary to use this link to log in. Please change your password.
Error message
Exception: Could not authenticate against the warehouse. Is the server down? in helper_base::get_read_auth() (line 1422 of D:\web sites\drupal7\sites\www.butterfly-monitoring.net\modules\iform\client_helpers\helper_base.php).
The website encountered an unexpected error. Please try again later. 

I tried several times.

**Comment by BirenRathod** [comment]
PostgreSQL service didn't start in the morning when system restarted. I'm already started to look into it.

**Comment by BirenRathod** [comment]
Hello 
This problem have been resolved now. the service has up and running.

**Comment by DavidRoy** [comment]
thanks

**Comment by Gary-van-Breda** [comment]
For future reference I had to go into the geoserver and re-enable the indicia datastore.

**Comment by BirenRathod** [comment]
I had re-enabled the indicia datastore. do you still experience any problem?

**Comment by xaviermestdagh** [comment]
Yes thanks I could log in correctly again.
Regards,
Xavier

**Comment by Gary-van-Breda** [comment]
Yes. When I attempted to use the site half an hour ago, the indicia geoserver data store was disabled, and had a little warning triangle against it. The WFS country lookup was not working. I re-enabled it, and it was then OK.

**Comment by xaviermestdagh** [comment]
Sorry to come again with this issue, but I can now only log in using the
one-time login link. It says that my password was well updated but when I
log out and log in again, my password is unrecognized.

**Comment by DavidRoy** [comment]
I have the same problem.  I have to reset my password everytime when logging in.
@BirenRathod can you look into this please
