### ISSUE TITLE
Error on Annual summary page - due to no data returned?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#16]
The eBMS annual summary page (http://www.butterfly-monitoring.net/annual-summary) includes unnecessary text when it does not return data:

Branch Manager location list lookup: missing Branch allocation attribute {Array ( [valuetable] => location_attribute_value [attrtable] => location_attribute [key] => location_id [fieldprefix] => locAttr [extraParams] => Array ( [auth_token] => ae194f1cd794e657e19742da681c1213e5819184 [nonce] => 2c94b842797737d5c6e442ce135eb72c0a019f79 ) [survey_id] => 2 [caching] => 1 [location_type_id] => 107 ) } : Country CMS User ID

**Comment by Gary-van-Breda** [comment]
Config error : name of Country alllocation attribute was wrong. I've changed this on the form, and checked all the other forms for similar config error (there weren't any).
Form now shows correctly (given that there is no data there).

**Comment by DavidRoy** [comment]
thanks for fixing.  The drop-down list should have option 'Country data' rather than 'Branch data'.  Also, could the text for the drop-down list just say 'Filter' not 'Filter by recorder'.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you unzip the attached file [node.16.en.zip](https://github.com/BiologicalRecordsCentre/eBMS/files/831874/node.16.en.zip), and put the resultant .php translation file
 into the iform/client_helpers/prebuilt_forms/lang directory? Thanks

**Comment by BirenRathod** [comment]
The file has been uploaded into that folder.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : sorry, I've got an updated version of the file: can you unzip and replace the file in iform/client_helpers/prebuilt_forms/lang?
[node.16.en.zip](https://github.com/BiologicalRecordsCentre/eBMS/files/874946/node.16.en.zip)
Thanks

**Comment by BirenRathod** [comment]
It has updated.
@Gary-van-Breda

**Comment by Gary-van-Breda** [comment]
@DavidRoy : all occurrence of Branch on the Annual summary page have been replaced with Country, and the labels in the control bar have been changed.
