### ISSUE TITLE
Upload guide document

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#18]
[eBMS Transect input system.pdf](https://github.com/BiologicalRecordsCentre/eBMS/files/790589/eBMS.Transect.input.system.pdf)

Make this file available for download via the 'here' link on http://www.butterfly-monitoring.net/mydata

Download the full guide to this site **here** (note that some elements of the guide will change when the site becomes fully live).

**Comment by BirenRathod** [comment]
The folder has been created and file has been uploaded. You could do via "File browser" tab appears under your "My account" link.
