### ISSUE TITLE
Download of "My Sites" SHP

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#19]
The download of the shapefile (in My Sites) produces this error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <ServiceExceptionReport version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wfs/1.0.0/OGC-exception.xsd"><ServiceException code="InvalidParameterValue" locator="typeName">
      Feature type indicia:section_gis_download_view unknown
</ServiceException></ServiceExceptionReport>

**Comment by BirenRathod** [comment]
@Gary-van-Breda, I have created indicia:section_gis_download_view  on the geoserver now.

**Comment by xaviermestdagh** [comment]
Works fine, thanks!
