### ISSUE TITLE
Language support for some Indicia pages

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/eBMS#20]
@Gary-van-Breda , There are some indicia pages which don't have language support , For example "My Walks" haven't got a page type option called "Report calendar grid". Due to that, if anybody want to configured the page in other language apart from English, is not possible. 

Also, is it possible to clone the same settings of each Indicia page into different language? At present, if you press the "Translate" button of any Indicia page, The configuration disappears. Which is too much work for anybody unless do you have any other suggestion to best to way translate any Indicia pages.

**Comment by Gary-van-Breda** [comment]
The Iform module has some translation abilities built in. This is generally done by the provision of files in the  client_helpers/prebuilt_forms/lang directory. At the moment the default language is English, and the other language translations are not there, except (bizarrely) a French version of the page you quoted: "My Walks". Is this what you mean?

**Comment by BirenRathod** [comment]
It is not only about the French version. you could probably find out through website when you go in "Translate" page and Press "add translation" link for any language. The page will open for creating new indicia page and there you couldn't find the option which mentioned above in drop down list of page type. So far I found for "My Walks" page. there may be more....

**Comment by BirenRathod** [comment]
I attached two screenshots here to understand better.
![screensot_lang1](https://cloud.githubusercontent.com/assets/5941255/23302648/6dc5a968-fa87-11e6-91e8-3ad01d6b6a5a.jpg)

![screensot_lang2](https://cloud.githubusercontent.com/assets/5941255/23302693/bb814e1e-fa87-11e6-8b4f-75a57a3124d1.jpg)

**Comment by Gary-van-Breda** [comment]
Untick the "Only show recommended page types" checkbox (even though it is shown ticked in the English form). This will give the full list.

**Comment by BirenRathod** [comment]
Ah, sorry I missed that part. Thanks  @Gary-van-Breda.
What about the second problem I mentioned above.

**Comment by Gary-van-Breda** [comment]
Sorry - I'm not sure I understand what you mean by the configuration disappears?

**Comment by BirenRathod** [comment]
What I mean is that why do we have to re-configure all those Indicia pages for any language which already exists in English.

**Comment by Gary-van-Breda** [comment]
I don't think you should need to: all we need is a language translation file for the node. Admittedly at the moment there aren't many, but it should be relatively simple. e.g. look at "My Walks" in French.
I'd hope that Drupal can handle the translation of the node title and the menu title.

**Comment by BirenRathod** [comment]
what does it mean by we need language translation file.........

Also Drupal can't handle to translate title, menu title and body text automatically, you need to actually translate and feed into it and save that page into particular language. For that you need to "add translation" to that language which will require reconfigure indicia page. Have a look the two pages created on the test site. http://192.171.199.230/ebms. one is regular Drupal page and another one is Indicia page.

**Comment by BirenRathod** [comment]
Also, I'm not talking about the translating of the stuff which brought through indicia. For e.g. the "Filter by site " drop down list or Name of the months appear on "My Walks" page.
