### ISSUE TITLE
Cross domain proxy issue

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#21]
There seems to be a cross domian proxy problem when using "butterfly-monitoring.net" rather than "www.butterfly-monitoring.net"

The place where I noticed it was entering a route on a site, where an ajax call is failing because its trying to call a www url from a non-www page.
This can also be seen if you try to use the masquerade autocomplete from butterfly-monitoring.net - it works OK from www.butterfly-monitoring.net.

@BirenRathod - please close if resolved

**Comment by BirenRathod** [comment]
This issue has resolved now.
