### ISSUE TITLE
Login password needing to be reset every time site used

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#22]
Reported by Xavier and David

**Comment by BirenRathod** [comment]
I have made changes on Global password limitation. Do you still experienced this problem?
Biren

**Comment by DavidRoy** [comment]
I still have this problem

**Comment by BirenRathod** [comment]
Yes, I got this, this is the problem when BOTCHA is stopping genuine URL to let login. I have disabled that now. Should be fine.

**Comment by DavidRoy** [comment]
Is the problem that the form requires 'username' rather than an email address.  Could the form accept either?

**Comment by BirenRathod** [comment]
No, it is nothing to do with that, it just BOTCHA do not accept the re-generated script from JavaScript. you should be fine to use either of those.

**Comment by DavidRoy** [comment]
Issue is still not resolved using either Chrome or IE

**Comment by BirenRathod** [comment]
Have you used the username or email address? please use username and see problem is still there.

**Comment by DavidRoy** [comment]
Works when using 'username'.  Hence my question about allowing either to be used!

**Comment by BirenRathod** [comment]
Yes, I got your concern. I was resolving first problem. The login problem for email address was there because the option for login via email hadn't been enabled. I have now enabled it.

**Comment by DavidRoy** [comment]
Still an issue if user starts typing in email address to request a replacement, then selects the email address from the list of stored email addresses for the form field.
