### ISSUE TITLE
Password reset request - overly sensitive

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#23]
When using the 'request new password' option, the email address is already populated.  But then if the 'email new password' button is selected, a warning message is given.

The only way to get the form to work is to type in an email address very slowly - the spam bot check is overly sensitive

![image](https://cloud.githubusercontent.com/assets/2699478/23652355/77df2a04-0320-11e7-8ad2-461718da2f95.png)

**Comment by BirenRathod** [comment]
This is relate to https://github.com/BiologicalRecordsCentre/eBMS/issues/22.

**Comment by DavidRoy** [comment]
Still an issue if user starts typing in email address to request a replacement, then selects the email address from the list of stored email addresses for the form field.

**Comment by BirenRathod** [comment]
would that be due to cookies?

**Comment by DavidRoy** [comment]
no, same happens when I remove cookies and try again

**Comment by BirenRathod** [comment]
I done using your email address and not seeing any problem.

**Comment by BirenRathod** [comment]
I have disabled the BOTCHA module and setup the CAPTCHA module.
