### ISSUE TITLE
Are scheduled tasks running on Warehouse2?

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/eBMS#24]
I'm looking at the EBMS annual summary page. It is not showing the data that has been entered, and I notice the summary builder scheduled task has not been run since 2017-02-06 09:38:42 (this is displayed on the warehouse Admin->Summariser page)

**Comment by BirenRathod** [comment]
Hello Gary

I don't understand, why is it not showing data in summary page and nothing showing in the log file also?

Here is screenshot, I took from the server.

![scheduled_tasks](https://cloud.githubusercontent.com/assets/5941255/23772911/ae8cd45c-0514-11e7-9fbd-3fb55a16f46a.jpg)

**Comment by BirenRathod** [comment]
Gary, it is not a problem of task scheduler running on the server but the problem in Scheduled_tasks has got some error. I just ran this http://warehouse2.indicia.org.uk/index.php/scheduled_tasks from the browser and it throws this error : 2017-03-09T22:11:58+00:00 ERROR : Weekstart month-day combination unrecognised {Jan/01} ,
does it make sense to you?

**Comment by Gary-van-Breda** [comment]
Thanks Biren
Configuration on Summariser page in warehouse changed: weekstart Apr/01 changed to Apr-01.
Scheduled task now completes.
Data displayed on annual summary.
Closing this issue.
