### ISSUE TITLE
Reliability field at section-level: explanation

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#25]
It might be necessary to add some explanation on values of the new field "Reliability". For instance as a text above the grid. 
_The field "Reliability" allows you to precise the count reliability at each section level.
1: Suitable conditions, the count reflects the butterfly abundance.
2: Unsuitable conditions (for instance too much wind, running cows arround the observer...). The count does not reflect the butterfly abundance altough some butterflies have been observed.  
3: The section could not be surveyed, for instance due to accessibility._

**Comment by xaviermestdagh** [comment]
@Gary-van-Breda Please do not forget this as it influences data encoding. I beleive a simple text box above the grid of observations is enough

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
Can you give me a zipped up copy of the IForm module on the EBMS site? I need to check the node specific language files, Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

Here is the ZIP file.
[iform.zip](https://github.com/BiologicalRecordsCentre/eBMS/files/1383348/iform.zip)

**Comment by Gary-van-Breda** [comment]
@xaviermestdagh : I have added a comment to the top of the page. Is this OK?

**Comment by xaviermestdagh** [comment]
Great!
