### ISSUE TITLE
Incomplete Iform module.

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/eBMS#29]
I’ve tried logging in and looking at some of the forms, but I am getting some 404 errors: there doesn’t seem to be anything coming back from the http://www.butterfly-monitoring.net/sites/www.butterfly-monitoring.net/modules/iform/media/js directory.

**Comment by BirenRathod** [comment]
Some reason media folder from repository hasn't been cloned completely. I have copied again all files from the old folder.
