### ISSUE TITLE
Section-level attribute - count reliability

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#3]
In our Luxembourg transect encoding form, we have a field at section level that describes how reliable were the counts on the sections, three values: 
* 1 means the counts could be done in good conditions and do represent the abundance at this time, 
* 2 means conditions were no good (e.g. cows running around, grass being cutted, too much wind or clouds...), so that the counts on the section is not representative of the abundance (observations could perhaps be made but are not representative...)
* 3 means the count could not be done on the section (e.g. observer could not access the section).
I suggest to add this section-level attribute in eBMS, but we should agree on a common list of values and respective definitions.

**Comment by Gary-van-Breda** [comment]
I have added this attribute to the warehouse and set up the walk entry form configuration so that this is present for Luxembourg sites only (at the moment - this can be changed). I have assumed that this is a section only attribute.
Is this to be made a mandatory field?

**Comment by xaviermestdagh** [comment]
Hello,
Yes in Luxembourg we set it as mandatory. If this attribute stays Luxembourg-specific in eBMS, I would keep it mandatory. If other countries use it, it should perhaps be discussed with them.

**Comment by DavidRoy** [comment]
It's ok to leave as mandatory for the whole system initially.

**Comment by Gary-van-Breda** [comment]
The current configuration is that the Reliability is present for Luxembourg transects only, and it is mandatory for them.
Do you want me to change this so it is present for all countries?

**Comment by DavidRoy** [comment]
That's fine.  We can review some of these questions as the system gets used
