### ISSUE TITLE
Create new site troubles - map display and "your route"

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#30]
- While creating a new site, LUX maps are not displayed (only google) when selecting "Luxembourg". BUT, when I reedit the site, that I go on the tab "Your Route" then back to tab "Site details", LUX maps appear...
- "Your route" tab only displays the frame with explanation, nothing else (no mapping tool, section related fields/buttons...).
=> not possible to create new sites.

**Comment by Gary-van-Breda** [comment]
I've downgraded the JQuery from 1.10 to 1.8: This should fix the Jaxvascript error that caused half the functionality to disappear, and fix the issues above.

**Comment by xaviermestdagh** [comment]
Thanks, it's fine!
