### ISSUE TITLE
User access to "Sites"

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#33]
A new user (Lionel L'Hoste) is not able to see sub elements like "My sites" or "My walks" from the menu "My data" (My data/Sites, My data/Walks...), so that he cannot create new sites nor encode walks...

**Comment by DavidRoy** [comment]
Lionel is now set with the right permissions.  Please let me know if not

**Comment by xaviermestdagh** [comment]
Thanks, I will ask him. Is a confirmation of access required from you each time a new user is created? Alain Dohet also created an account today, with the aim to encode in Luxembourg.

**Comment by DavidRoy** [comment]
I've activated Alain's account.  When the site is fully up-and-running we'll remove the confirmation step - would you prefer that?

**Comment by xaviermestdagh** [comment]
Thanks. Perhaps yes, but as you said once it is fully up-and-running.

**Comment by xaviermestdagh** [comment]
@DavidRoy I just asked to a first set of observers (list here below) to encode one of their site, I will then look how data are encoded, if it's ok. So could you activate also their account once they are registred? Thanks have a nice day
"Michelle Clemens" <m.clemens@naturemwelt.lu>, "Mireille Molitor" <m.molitor@naturemwelt.lu>, Jenny Renaut/LIST, hellersk@pt.lu, "Gérard Schmidt" <gla.schmidt@gmail.com>,

**Comment by DavidRoy** [comment]
Will do.  If they (or you) let me know when they've registered, I'll approve straight away

**Comment by xaviermestdagh** [comment]
Thanks, unfortunately I am not in the same place than them so I don't know when.

**Comment by DavidRoy** [comment]
ok, I'll keep an eye out for registrations

**Comment by DavidRoy** [comment]
@Gary-van-Breda - please can you confirm the drupal 'roles' and configuration that need to be set for:
1. A standard data recorder
2. A country co-ordinator (e.g. for access to 'Country sites/walks' reports)
3. How this relates to the transect_allocation page (http://www.butterfly-monitoring.net/transects-allocation)

**Comment by xaviermestdagh** [comment]
Yes indeed, for the moment I cannot see sites, walks and data created in Luxembourg by users, which would be essential for country co-ordinator.

**Comment by xaviermestdagh** [comment]
@DavidRoy Michelle Clemens (LU user) says she is not authorized to enter a site. Is that related to somehting on your side?

**Comment by DavidRoy** [comment]
@xaviermestdagh Michelle's account should now be setup. as is Kevin Jans and Marcel Hellers.  Please let me know if any problems.

**Comment by xaviermestdagh** [comment]
Thanks, but I don't know Kevin Jans. In these cases, is it possible for me to contact him in ordre for instance to check if the protocol is followed?

**Comment by DavidRoy** [comment]
Yes, I'll send you his contact details

**Comment by DavidRoy** [comment]
@Gary-van-Breda - raising this again.  Point 2 is urgent

please can you confirm the drupal 'roles' and configuration that need to be set for:

1. A standard data recorder
2. A country co-ordinator (e.g. for access to 'Country sites/walks' reports)
3. How this relates to the transect_allocation page (http://www.butterfly-monitoring.net/transects-allocation)

**Comment by Gary-van-Breda** [comment]
A standard data recorder should be given the EBMS role "DATA RECORDER"
The country coordinator should be given the EBMS role "COUNTRY MANAGER": this allows access to the "Country Sites", "Country Walks" pages.
At the moment the access to the Transects Allocation page is only given to the next level up, not "Country Manager" - do I take it this is not what you require?

**Comment by xaviermestdagh** [comment]
Would it be possible to provide transect allocation rights to the country manager (i e for the transect of his country)?

Envoyé depuis IBM Verse


   Gary-van-Breda --- Re: [BiologicalRecordsCentre/eBMS] User access to "Sites" (#33) --- 
    De :"Gary-van-Breda" <notifications@github.com>A :"BiologicalRecordsCentre/eBMS" <eBMS@noreply.github.com>Cc :"xaviermestdagh" <xavier.mestdagh@list.lu>, "Mention" <mention@noreply.github.com>Date :ven., 12 mai 2017 15:51Objet :Re: [BiologicalRecordsCentre/eBMS] User access to "Sites" (#33)
  
  A standard data recorder should be given the EBMS role "DATA RECORDER" The country coordinator should be given the EBMS role "COUNTRY MANAGER": this allows access to the "Country Sites", "Country Walks" pages. At the moment the access to the Transects Allocation page is only given to the next level up, not "Country Manager" - do I take it this is not what you require?

**Comment by Gary-van-Breda** [comment]
OK: rights to access the transect allocation page have been given to the country managers.
But - looks like there is a missing report on the warehouse, without which this page won't work:

@BirenRathod or @JimBacon : do you know when warehouse2 is going to get release 1.31.0 or later? There is a report reports/reports_for_prebuilt_forms/UKBMS/ebms_region_locations.xml that gets added in that release.

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda, you caught me while I was upgrading the warehouse2. please check if it has got your updates.

**Comment by Gary-van-Breda** [comment]
Report is present, and page now works.

**Comment by Gary-van-Breda** [comment]
Well it looked like it did: there is some ajax issue I'll now look into.

**Comment by DavidRoy** [comment]
@Gary-van-Breda 

I'm not sure what 'only given to the next level up' means below.  Can you explain?

The country coordinator should be given the EBMS role "COUNTRY MANAGER": this allows access to the "Country Sites", "Country Walks" pages.
At the moment the access to the Transects Allocation page is **_only given to the next level up_**, not "Country Manager" - do I take it this is not what you require?

**Comment by xaviermestdagh** [comment]
I have now access to the "Transects Allocation" page, but 
- it seems it does not work. Do I just need to check the "Allocated?" of the corresponding lines?
- a click on "Edit" in the grid redirects to an empty form (like to create a new site).   
- I still don't have a view on all sites and walks created in Luxembourg through Country Sites and Country Walks.

**Comment by Gary-van-Breda** [comment]
RE Davids comment : apologies - I have a sort of Heirarchy of access in my head...
1) Administrator
2) Country Manager
3) Normal User (Data recorder)

So the Transect Allocation was only available to the Administrators - now no longer the case.
There is an issue with the saving of the allocation - I am investigating.

**Comment by xaviermestdagh** [comment]
@Gary-van-Breda Any progress on the saving of the allocation?

**Comment by xaviermestdagh** [comment]
@Gary-van-Breda Any update? Could you identify the trouble?

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you deploy the develop branch version of the ebms_transects_allocation form into both the EBMS and UKBMS D7 environments?
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/ebms_transects_allocation.php

**Comment by BirenRathod** [comment]
This has uploaded on UKBMS D7 and EBMS live site.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : There are obviously some differences between my development environment and Live. Do you mind if we try again? Can you deploy the develop branch version of the ebms_transects_allocation form into both the EBMS and UKBMS D7 environments?
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/ebms_transects_allocation.php

**Comment by BirenRathod** [comment]
It has now updated. do you want me to update the report_calendar_grid.php file too?

**Comment by Gary-van-Breda** [comment]
@Biren I'm getting a Cross Origin request blocked when I access 

> http://warehouse2.indicia.org.uk//index.php/services/data/location_attribute_value

 but not when I do 

> http://warehouse2.indicia.org.uk//index.php/services/report/requestReport

Both return json. Is there a reason for this? This also happens on warehouse1 for UKBMS.

**Comment by Gary-van-Breda** [comment]
The report_calendar_grid.php that I sent you should match the develop branch.

**Comment by xaviermestdagh** [comment]
Thanks. 
- Allocating sites is now working (newly allocated sites appear in my "My sites"), 
- "edit" button from this page redirects to an empty form. Is that normal? 
- What's the difference between sites in "My Sites" and in "Country Sites" ? In the last one I only can see "

**Comment by xaviermestdagh** [comment]
Lionel created the site RN Rosport in Luxembourg. From my account, this site is allocated to Germany, and not to Luxembourg. However, when Lionel edits this site, it is well allocated to Luxembourg... What's wrong ?!

**Comment by Gary-van-Breda** [comment]
Note the cross origin request block mentioned above means that the transect allocation form can only allocated people, it can not de-allocate them.
Edit button: this is an issue, it should display the site. There is a URL parameter naming issue.
The My sites and Country sites are very similar: the allocation is done using a different attribute, and only some people (country managers) can have sites allocated to them at a country level.

**Comment by xaviermestdagh** [comment]
@Gary-van-Breda Thanks for details. Regarding the site RN Rosport, why is it allocated to Germany from my login and to Luxembourg from Lionel's login? The site is close to the border, but clearly inside Luxembourg.

**Comment by DavidRoy** [comment]
Bumping this back to @BirenRathod 

From Gary:
I'm getting a Cross Origin request blocked when I access

http://warehouse2.indicia.org.uk//index.php/services/data/location_attribute_value
but not when I do

http://warehouse2.indicia.org.uk//index.php/services/report/requestReport
Both return json. Is there a reason for this? This also happens on warehouse1 for UKBMS.

**Comment by Gary-van-Breda** [comment]
@xaviermestdagh : the trouble is that the Luxembourg location record boundary is not very good: look at RN Rosport (http://www.butterfly-monitoring.net/ebms-site-details?id=413) on the map, switch off the lux topography in the layer switcher: you will see a red dashed line going through the map: this is the Luxembourg record boundary, and it very obviously does not match up with the actual boundary. This means the check thinks RN Rosprt is outside Luxembourg.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : I also don't get a COR blocked if I use:
http://warehouse2.indicia.org.uk/index.php/services/data/taxa_taxon_list

**Comment by xaviermestdagh** [comment]
[Borders.zip](https://github.com/BiologicalRecordsCentre/eBMS/files/1075044/Borders.zip)
@Gary-van-Breda Any idea how to fix this problem of broders? I have this shapefile of european borders if it helps...

**Comment by Gary-van-Breda** [comment]
We can convert the shapefile into SQL statements and upload them: the current PHP system (not Indicia) don't allow a direct upload anymore (the ability to read the file has been dropped).

**Comment by BirenRathod** [comment]
@Gary-van-Breda, I didn't get your comment about PHP system direct upload don't allow. I'm sure you can upload shape file into warehouse (via website). It is still supporting.

**Comment by Gary-van-Breda** [comment]
Sorry, my mistake - it is OK.

**Comment by DavidRoy** [comment]
@Gary-van-Breda @BirenRathod 
Where are we with this issue?

**Comment by Gary-van-Breda** [comment]
There seems to be 3 issues on the go
1) Edit link in Transect allocation form not working: @BirenRathod can you deploy the develop branch version of the following file into the UKBMS D7 and EBMS websites:
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/js/ebms_transects_allocation.js
2) Cross Origin request issue: This is still outstanding, and will need to be sorted by someone like @BirenRathod 
3) The boundaries of the countries are not accurate enough: see new zip file given by @xaviermestdagh above. I haven't had a chance to look at this. I'm not sure what this comes under or who should deal with it - there was another issue aised (now closed) about uploading the country boundaries.

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda 

1. This has updated now.
2. Where do you see Cross Origin request? send me some more details.
3. I just tried to access through QGIS and no luck. Any idea?

Biren

**Comment by Gary-van-Breda** [comment]
1: Form configuration setup on EBMS and UKBMS - now works.
2: I'm using Firefox. Log in to site as eother admin or a country manager: go to transect allocation form (My Data->Sites->Transects Allocation). On the page, select Normal User Assignment; Country Luxembourg: Site "GvB Test Site Lux 1", user admin, and then press the search. When you deselect the checkbox on the admin user row, it will uncheck and send a data request to the warehouse to fetch all the location_attribute_value records that could be there - this fails the COR. It should then delete these, but that doesn't happen.

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda 
2. I added the value for CORS in IIS on the server now. It should be ok now.

**Comment by BirenRathod** [comment]
@Gary-van-Breda, I just noticed that CORS problem is exists on UKBMS too. Check on Site Assignment page. I'm resolving this now.

**Comment by BirenRathod** [comment]
@Gary-van-Breda, I have added value for CORS on warehouse1 too.

**Comment by Gary-van-Breda** [comment]
COR looks ok now on warehouse2. I haven't checked warehouse1
3. I've just tried to upload the borders.zip file into my warehouse - I got a shape type error.

**Comment by BirenRathod** [comment]
@Gary-van-Breda, yes, that is right. Shape file is not in right format.

**Comment by Gary-van-Breda** [comment]
@xaviermestdagh : Do you have another shape file?
I've tried looking at the file, and it seems to be OK until the Albania record (record 44).
I think we should concentrate on the countries that directly affect you, so if possible can you just give us a shape file with Belgium, France, Germany and Luxembourg.

**Comment by xaviermestdagh** [comment]
Sorry Gary, I am out of office until Monday. Have a nice day

Xavier Mestdagh


   Gary-van-Breda --- Re: [BiologicalRecordsCentre/eBMS] User access to "Sites" (#33) --- 
    De :"Gary-van-Breda" <notifications@github.com>A :"BiologicalRecordsCentre/eBMS" <eBMS@noreply.github.com>Cc :"xaviermestdagh" <xavier.mestdagh@list.lu>, "Mention" <mention@noreply.github.com>Date :mer., 11 oct. 2017 23:20Objet :Re: [BiologicalRecordsCentre/eBMS] User access to "Sites" (#33)
  
  @xaviermestdagh : Do you have another shape file? I've tried looking at the file, and it seems to be OK until the Albania record (record 44). I think we should concentrate on the countries that directly affect you, so if possible can you just give us a shape file with Belgium, France, Germany and Luxembourg.

**Comment by xaviermestdagh** [comment]
[Borders_EU.zip](https://github.com/BiologicalRecordsCentre/eBMS/files/1386750/Borders_EU.zip)
Yes here attached. I extracted the shp of B, L, D and F from the european one. Regarding Luxembourg, the borders stick well to the reality. The Geographic Coordonate system is:
 
GCS_WGS_1984
WKID: 4326 Authority: EPSG

Angular Unit: Degree (0.0174532925199433)
Prime Meridian: Greenwich (0.0)
Datum: D_WGS_1984
  Spheroid: WGS_1984
    Semimajor Axis: 6378137.0
    Semiminor Axis: 6356752.314245179
    Inverse Flattening: 298.257223563

Is that what you needed?

**Comment by Gary-van-Breda** [comment]
Borders updated on L, F, D, B in live warehouse2.
Looks a lot better near RN Rosport: now is definitely inside Luxembourg.
@xaviermestdagh : are you happy to close this issue now?

**Comment by xaviermestdagh** [comment]
Yes indeed it seems great, Thanks!

**Comment by xaviermestdagh** [comment]
Sorry Gary, during the creation of a new site (Site details tab), there is
now warning while selecting a point as site coordinates.

Change Country?
A change in country has been detected. Do you wish to set the country to
the new value? This may lead to changes in the acceptable number of
sections, and/or a different set of maps.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can we restart the geoserver for warehouse2? Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

It is already on. here is the URL http://warehouse2.indicia.org.uk:8080/geoserver/web/

**Comment by Gary-van-Breda** [comment]
@BirenRathod : sorry, what I meant was could you stop it, then restart it. It is giving some odd results to some WFS queries.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I have restarted now.

**Comment by Gary-van-Breda** [comment]
Thanks @BirenRathod : are there any error messages in the geoserver or postgres log files?

**Comment by Gary-van-Breda** [comment]
Again, I think this has been addressed by the switch to ABLE.
Reassigning to Xavier to review and hopefully close.
