### ISSUE TITLE
List of countries in account preferences

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#34]
In the "Where you record" tab, the "Record location" dropdown list displays also all sections created... (in addition of countries).

**Comment by Gary-van-Breda** [comment]
@BirenRathod 
I don't have access to the MySql database for the EBMS Drupal Website. Please could you run the following statement in the Drupal Mysql database, EBMS only (not the warehouse Postgres database):

INSERT INTO `variable`(`name`, `value`) VALUES ('indicia_profile_location_type_id','i:213;') ;

Thanks

**Comment by BirenRathod** [comment]
Added this line to variable table.

**Comment by Gary-van-Breda** [comment]
I've just checked and the "Record location" now only displays countries.
@xaviermestdagh : if you are happy, shall we close this issue?

**Comment by xaviermestdagh** [comment]
Great thanks.
