### ISSUE TITLE
Notice/warning on transect allocation page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#35]
http://www.butterfly-monitoring.net/transects-allocation

Is showing the following message when logged in as admin
Notice: Undefined index: allocation_config_list in iform_ebms_transects_allocation::_identify_current_type() (line 140 of D:\web sites\drupal7\sites\www.butterfly-monitoring.net\modules\iform\client_helpers\prebuilt_forms\ebms_transects_allocation.php).

Warning: Invalid argument supplied for foreach() in iform_ebms_transects_allocation::_identify_current_type() (line 142 of D:\web sites\drupal7\sites\www.butterfly-monitoring.net\modules\iform\client_helpers\prebuilt_forms\ebms_transects_allocation.php).

**Comment by Gary-van-Breda** [comment]
This is now fixed (config issue with more up to date version of form).
Note there is another issue with this form at the moment that is being investigated (see #33)

**Comment by DavidRoy** [comment]
@Gary-van-Breda is the transect allocation page now ok?  Can we close this issue?

**Comment by Gary-van-Breda** [comment]
Yes, its working now (ignoring the problem of the boundaries of the countries being inaccurate)

**Comment by DavidRoy** [comment]
Thanks.  We'll look at boundary accuracy separately.
