### ISSUE TITLE
Section grid update

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#37]
In the species grid of the walk data entrs form, the column heading do not freeze unless when you add manually a new species to the list. 
If you add manually a species, it freezes the heading, but the selected column (that got the focus) do not turn from green to white (like it does when the column is not freezed). 
It's perhaps a detail but already highlighted as confusing by two users...

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you deploy the following file into both the UKBMS and EBMS sites:
[ukbms_sectioned_transects_input_sample.zip](https://github.com/BiologicalRecordsCentre/eBMS/files/1397964/ukbms_sectioned_transects_input_sample.zip)

It should be deployed into iform/client_helpers/prebuilt_forms/js

Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I copied this file on to both sites.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : Thanks
@xaviermestdagh : Changes for both these points have now been deployed. Can you check you are happy with them? If so, then this issue can be closed.
(In addition some extra fixes have been put in, as the headers were coming out the wrong size in some situations).

**Comment by xaviermestdagh** [comment]
great, thanks!
