### ISSUE TITLE
Access to butterfly-monitoring.net

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#38]
@Gary-van-Breda I have an unexpected error to access to the website since last week:

PDOException: SQLSTATE[HY000] [1862] Your password has expired. To log in you must change it using a client that supports expired passwords. in lock_may_be_available() (line 167 of D:\web sites\drupal7\includes\lock.inc).

**Comment by BirenRathod** [comment]
I have removed the default password limit in the database. It should not display expire password message in future.

**Comment by xaviermestdagh** [comment]
Thanks!
