### ISSUE TITLE
Management of moving sections

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#4]
We started in 2010 with transect in Luxembourg and even on this short period we had to move some sections mainly due to accessibility, new buildings, vegetation, crop reparcelling... I guess you all know that?!
How do we manage these modifications of sections, the numbering, the history (related observations...)... in eBMS?

**Comment by xaviermestdagh** [comment]
A solution I see is that if one or several sections need to move, a complete new site is created in eBMS by the observer. Transect and sections will be associated to new IDs in the database (and therefore in trend analysis!), although unmoved sections are geographically the same. @DavidRoy what do you think about that?

**Comment by DavidRoy** [comment]
Yes, that is our recommendation in the UK.  If any sections change, we treat as a new transect.
