### ISSUE TITLE
Name of complexe of species

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#40]
For complexes of species, the English name is used instead of latin name (e.g. in reports, the field "Species" includes latin names for single species and english names for complexes of species).

**Comment by Gary-van-Breda** [comment]
Generally there is a philosophy (carried over from UKBMS) that the "species" displays the common name if available, and the "preferred" taxon will display the latin name. On the EBMS site, only the species complexes have common names defined: for the other species where there is no common name, so the "species" defaults to the preferred (latin) name.

For the reports, there should always be two columns, giving both values.

On the forms, the same philosophy is carried through: the species will be generally displayed as the common name, and a tooltip (hover tip) will give the preferred latin name.

@xaviermestdagh : Do you want to swap these around, so the primary label for a species is the latin name, and the secondary is the common name?

Note that the current arrangement is a carry over from UKBMS, where there is a single primary language, so the use of the default common name (in English) is more user friendly. This may not be the case in the pan-European situation. @DavidRoy : do you have any preferences?

**Comment by DavidRoy** [comment]
I'm happy to go with @xaviermestdagh 's recommendation.  My initial reaction is to give the latin name as the primary name for eBMS

**Comment by xaviermestdagh** [comment]
As introduced by Gary, I believe that in a pan-European situation the latin name should be the primary label.

**Comment by DavidRoy** [comment]
agreed

**Comment by Gary-van-Breda** [comment]
@JimBacon or @BirenRathod 
Can I have the following files deployed into the EBMS iform ?
[client_helpers.zip](https://github.com/BiologicalRecordsCentre/eBMS/files/1531711/client_helpers.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

I have deployed this code to EBMS site.

**Comment by Gary-van-Breda** [comment]
Forms configured to use latin names as primary:

- Annual Summary
- Section Plot
- Sites/Visits Summary
- Walk Data Entry
- Year by Year Index Plot

Other forms are all OK.
