### ISSUE TITLE
Annual Summary - 404 error while selecting "Country data"

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#45]
A 404 error appears when selecting "Country data" in the filter.

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
[errno] => 0 [status] => 404 [request] => index.php/services/data/summary_occurrence?mode=json&columns=date_start%2Cdate_end%2Cdate_type%2Ctype%2Cperiod_number%2Ctaxa_taxon_list_id%2Ctaxonomic_sort_order%2Ctaxon%2Cpreferred_taxon%2Cdefault_common_name%2Ctaxon_meaning_id%2Ccount%2Cestimate&auth_token=b06b61e420a4bf120a384d6bd3437beb60f561de&user_id=NULL&nonce=69d54f4fb215517e9571386f4532e5d6d9e58976&year=2017&survey_id=2&taxon_list_id=1&query=%257B%2522in%2522%253A%255B%2522location_id%2522%252C%255B%2522394%2522%252C%2522516%2522%252C%2522431%2522%252C%2522446%2522%252C%2522413%2522%252C%2522497%2522%252C%2522377%2522%252C%2522571%2522%252C%2522580%2522%252C%2522597%2522%252C%2522610%2522%252C%2522620%2522%252C%2522554%2522%252C%2522666%2522%252C%2522659%2522%252C%2522652%2522%252C%2522675%2522%252C%2522637%2522%252C%2522686%2522%252C%2522888%2522%252C%2522855%2522%252C%2522718%2522%252C%2522699%2522%252C%2522716%2522%252C%2522744%2522%252C%2522785%2522%252C%2522753%2522%252C%2522794%2522%252C%2522800%2522%252C%2522806%2522%252C%2522779%2522%252C%2522811%2522%252C%2522826%2522%252C%2522766%2522%252C%2522832%2522%252C%2522735%2522%252C%2522761%2522%252C%2522819%2522%252C%2522770%2522%252C%2522943%2522%252C%2522960%2522%252C%25221060%2522%252C%25221072%2522%252C%2522972%2522%252C%25221084%2522%252C%25221009%2522%252C%25221101%2522%252C%2522986%2522%252C%2522909%2522%252C%2522944%2522%252C%25221043%2522%252C%2522926%2522%252C%25221026%2522%252C%25221138%2522%252C%25221118%2522%252C%25221144%2522%252C%25221168%2522%252C%25221131%2522%252C%25221157%2522%252C%25221171%2522%252C%25221188%2522%252C%25221239%2522%252C%25221256%2522%252C%25221205%2522%252C%25221222%2522%252C%25221291%2522%252C%25221273%2522%252C%25221295%2522%252C%25221304%2522%252C%25221363%2522%252C%25221356%2522%252C%25221321%2522%252C%25221331%2522%252C%25221340%2522%252C%25221371%2522%252C%25221429%2522%252C%25221509%2522%252C%25221524%2522%252C%25221446%2522%252C%25221462%2522%252C%25221478%2522%252C%25221493%2522%252C%25221376%2522%252C%25221400%2522%252C%25221411%2522%252C%25221392%2522%252C%25221416%2522%252C%25221544%2522%255D%255D%257D )

**Comment by xaviermestdagh** [comment]
@Gary-van-Breda @BirenRathod Does one of you could have a look to this? It makes data extraction unavailable...
Thanks!

**Comment by BirenRathod** [comment]
It works for individual site but not for "all my sites". any idea?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
This has resolved now

**Comment by xaviermestdagh** [comment]
Thanks!
