### ISSUE TITLE
Site with Null value as country 

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#46]
@Gary-van-Breda The site name "Dreiländereck" with the code "ebms:Luxembourg:90" has Null value for "Country" (when displayed using the filter of the Transect Allocation tool).
If I did not compare the total number of sites from "Country sites" and "All Sites", I could not discover that this site was existing (because not visible when selecting "Luxembourg" in the Transect allocation tool). 
What are the circumstances that leaded to that situation for that site? Is that fixable?

**Comment by Gary-van-Breda** [comment]
I think the problem here is that, even with the improved country boundaries, this site is outside the Luxembourg country location record - this can be seen from the red dotted boundary line.
We could add a buffer around the country boundary when checking if a site is within a country - I think 100m would work. What do you think?

**Comment by xaviermestdagh** [comment]
Yes if easy for you to set up, but isn't it going to allocate
German/French/Belgian sites to Luxembourg?

**Comment by Gary-van-Breda** [comment]
Yes it would, if there were any!

Other options: change the way the page works, so it looks up the country attribute on the location record rather than check if it is within the boundary? This is more work to do.

We could display the code and/or the country attribute on the table for each site.

**Comment by xaviermestdagh** [comment]
We hope more BMS are going to join, and of course this issue is not Luxembourg specific...
@DavidRoy If recorders select the country (including regional BMS!?) in a dropdown list during the creation of the site, wouldn't be great to use this value as a reference?
@Gary-van-Breda How much additional work would it require?

**Comment by Gary-van-Breda** [comment]
Probably half a day

**Comment by Gary-van-Breda** [comment]
I think this has been overtaken by the changes done to EBMS in the conversion to ABLE.
No longer applicable: the site in question is now within the Luxembourg countrie location record boundary.
It is now possible to assign a site to a country, even if it is outside the boundary (admittedly with a warning).
Bouncing to Xavier to review and hopefully close.

**Comment by xaviermestdagh** [comment]
I didn't face this trouble again, assuming now ok as well.
