### ISSUE TITLE
move eBMS website to Pantheon web host

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#51]
move to Pantheon, including a test site

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Did you change password for admin on http://dev-butterfly-monitoring.pantheonsite.io/? Could you reinstate its original one which I sent you text.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : No I didn't. I have a Backup/migrate database I can re-load if that helps.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Could you re-instate the password?

**Comment by Gary-van-Breda** [comment]
@BirenRathod I have re-instated the admin password to the value in the last text you sent me.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

Thank for re-instating a password. I can now logged in.

**Comment by DavidRoy** [comment]
Closing as now covered by ABLE
