### ISSUE TITLE
Error translating a page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#52]
Error message when saving a page translation: http://www.butterfly-monitoring.net/it/node/add/iform?translation=7&target=it

Steps to repeat error:
1. Login as Admin
2. Goto 'My sites' page. http://www.butterfly-monitoring.net/sites-list
3. Click on 'Translate' tab
4. click on 'Add translation' for Italiano
5. Make edits to Body text
6. Click on save

Error message = 
This page isn’t working www.butterfly-monitoring.net is currently unable to handle this request.
HTTP ERROR 500

**Comment by BirenRathod** [comment]
@DavidRoy 

I found no problem. May be you haven't added the iform settings . Although, Columns stiil require to add in the "Reports settings" .

**Comment by DavidRoy** [comment]
Closing as now covered by ABLE
