### ISSUE TITLE
Duplicated Internal eBMS site code

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#53]
Hello,
There are several sites in Luxembourg in the surrounding of Findel (Findel1, Findel2,... Findel10) having the same site code (EBMS:Luxembourg:106). Is there something wrong the user could have done? Would it be possible to fix this?
Thanks in advance,
Xavier

**Comment by xaviermestdagh** [comment]
@Gary-van-Breda or @BirenRathod 
Could you have a look to this? Two site codes (105 and 106) seem affected by replications, respectively 2x and 12x. The field Site name still provide a unique name for each transect.

**Comment by Gary-van-Breda** [comment]
This form is being completely rewritten as part of the Drupal 8 conversion for ABLE.
I'll check the current data though.

**Comment by xaviermestdagh** [comment]
@Gary-van-Breda 
Please do not forget this still ongoing issue! Thanks in advance.

**Comment by Gary-van-Breda** [comment]
Code bugfix applied to prevent caching of list of codes.
All codes updated: now no duplicates.
Affected all countries.
Bouncing back to Xavier to check, and hopefully close.
