### ISSUE TITLE
Transects Allocation - empty "Country" dropdown list 

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#56]
Hello @Gary-van-Breda 
The field "Country" is empty in the Transects Allocation page. Best wishes. 
![image](https://user-images.githubusercontent.com/24294138/58806054-9c866780-8615-11e9-9fa2-8cf4277be6cf.png)

**Comment by Gary-van-Breda** [comment]
This resulted from the temporary change to the warehouse configuration today: when it was swapped to warehouse1/ID118 all the required attributes etc were not set up on pointed to survey, and the location_types which specify a location as a "country" are all different.
Now this has been reverted to warehouse2, this should now be sorted.

**Comment by xaviermestdagh** [comment]
Great it works. Thanks!
