### ISSUE TITLE
Zoom in the map to last level

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#57]
When zooming the map in, the last level induces a trouble. The map is then blocked and it is not possible to work on it anymore. This last level provides interesting details to draw sections. 
![image](https://user-images.githubusercontent.com/24294138/58860484-7c55b780-86ac-11e9-8b88-7e1432faafc1.png)

**Comment by xaviermestdagh** [comment]
@Gary-van-Breda I guess you knows better about this

**Comment by Gary-van-Breda** [comment]
Fixed: form config for the last zoom had an invalid resolution.

**Comment by xaviermestdagh** [comment]
great!
