### ISSUE TITLE
Wrong page for transect allocation

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#58]
Hello,
The "Transects Allocation" redirects to the following link dispaying the following page. The allocation tool is therefore not accessible.  
https://butterfly-monitoring.net/asignacion-de-transectos
![image](https://user-images.githubusercontent.com/24294138/60658520-a3420d80-9e53-11e9-9c1c-f89b57afdd57.png)

**Comment by DavidRoy** [comment]
Apologies.  A few pages have been affected by translations.  This page should now be ok.  Please report any other pages with this problem.
