### ISSUE TITLE
National maps and geographical coordinate system

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#60]
Would it still be possible to use national map providers once the country is selected? For Luxembourg, maps from the map.geoportal.lu (topo map + aerial picture with transparency). In nature reserves for instance, landmarks of sections are often associated to small landscape features (tree, cliff, corner of a parcel...) that are not displayed on OSM or google maps. 
It was previously possible to select the national epsg (2169 for luxembourg), and coordinates of the cursor in the map area (section details) were displayed in the selected epsg. Is that still possible to have?

**Comment by Gary-van-Breda** [comment]
Two issues here: There was a recent update the the Indicia modules, and the Nuts2 regional data was loaded. This meant 1) the Maps where not being processed properly, and 2) there are now 2 public locations with the name Luxembourg.
Both issues now fixed, so the Luxembourg specific functionality is now working again - maps and 2169 sref system. (1) also meant the coordinate output was not initialised properly - this is now working as well.

**Comment by xaviermestdagh** [comment]
That's great, thanks.
