### ISSUE TITLE
Additional location attribute - linear features

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#7]
Additional category for classifying transect routes as to whether they cover linear features:

Requires new location attribute: Linear habitat
Values are: 
Not assigned (default value)
Not linear habitat
Field margin
Forest edge
Road/path
Ditch
Hedge
River/pond bank

**Comment by Gary-van-Breda** [comment]
I have added this location attribute to the Live site configuration.
Can I confirm it is for the Transect Section Routes, not the Transects themselves?
Also is it to be made mandatory?

**Comment by DavidRoy** [comment]
Yes, transect section routes.  Mandatory please

**Comment by Gary-van-Breda** [comment]
OK, configuration now done: Sections only, mandatory.

**Comment by xaviermestdagh** [comment]
@DavidRoy It seems this topic can be close?
