### ISSUE TITLE
Number of sections should be able to be set by user

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/eBMS#9]
Currently, the number of sections is set at 15 and not editable (greyed out) on site details:
http://www.butterfly-monitoring.net/ebms-site-details

The user should be able to set the number of sections, between 1 and 16 (16 is the maximum)

**Comment by Gary-van-Breda** [comment]
I've changed the config so that non-Luxembourg countries can have a variable number of sections, between and including 1 to 16.
Xavier: am i correct in saying that the Luxembourg transects are all 16 sections, or should they be variable as well?

**Comment by xaviermestdagh** [comment]
Hello,
Thanks. Yes we also have a variable number of sections by transects, up to 16.

**Comment by Gary-van-Breda** [comment]
OK configuration changed. All sites can have a variable number of sections, 1 to 16 inclusive.
The only current difference between Luxembourg and the other countries is the maps used, but as I've emailed you Xavier, there seems to a permissions issue with these maps.

**Comment by Gary-van-Breda** [comment]
I have contacted ACT to get their support on the Luxembourg maps issue.

**Comment by xaviermestdagh** [comment]
in http://butterfly-monitoring.net/ebms-site-details, entering for instance "11" in the cell "No. of sections:" produces the error message "Please enter a value greater than or equal to 16." 
==> no possible to create a site with less than 16 sections.
(Thanks for the Luxembourg maps!)

**Comment by Gary-van-Breda** [comment]
Bugfix just deployed to live. Minimum value now fixed.
